### PR TITLE
Added Cogent route option, removed FiberRing options from routing

### PR DESCRIPTION
**Pull request by mattjanicki**
Some of the servers changed within Feral routing options (Cogent was added and FiberRing servers were removed), so I simply altered the script to update that and gave it a new version number to reflect the change.

### CODE REVIEW

**Comment by frankthetank7254** [comment]
thanks for the pull, im having trouble with some routes from home, so I'm going to test this tomorrow, then merge it if all goes well

**Comment by mattjanicki** [comment]
Sure give it a shot.

**Comment by mattjanicki** [comment]
Did you get a chance to check it out?

**Comment by frankthetank7254** [comment]
sorry it took so long!

**Comment by mattjanicki** [comment]
Hah no worries.  I'm just glad the script's updated:)

**Pull request merged**
